#!/usr/bin/env bash
# Search common macOS / Wine / CrossOver locations for Yuri's Revenge (gamemd.exe).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/paths.local"
FOUND=()

candidates=(
  "${HOME}/Games/YR"
  "${HOME}/Games/Red Alert 2"
  "${HOME}/Games/Yuri's Revenge"
  "${HOME}/Games/RA2"
  "${HOME}/Library/Application Support/Steam/steamapps/common/Command and Conquer Red Alert II"
  "${HOME}/Library/Application Support/Steam/steamapps/common/Red Alert 2"
)

# CrossOver bottles (any bottle drive_c Program Files* with gamemd)
if [[ -d "${HOME}/Library/Application Support/CrossOver/Bottles" ]]; then
  while IFS= read -r -d '' f; do
    candidates+=("$(dirname "$f")")
  done < <(find "${HOME}/Library/Application Support/CrossOver/Bottles" -iname 'gamemd.exe' -print0 2>/dev/null || true)
fi

# Wine prefixes
for base in "${HOME}/.wine" "${HOME}/.local/share/wineprefixes"; do
  if [[ -d "$base" ]]; then
    while IFS= read -r -d '' f; do
      candidates+=("$(dirname "$f")")
    done < <(find "$base" -iname 'gamemd.exe' -print0 2>/dev/null || true)
  fi
done

# Optional: paths.local override already present
if [[ -f "$OUT" ]]; then
  # shellcheck disable=SC1090
  source "$OUT" || true
  if [[ -n "${GAME_DIR:-}" && -f "${GAME_DIR}/gamemd.exe" ]]; then
    FOUND+=("$GAME_DIR")
  fi
fi

for d in "${candidates[@]}"; do
  if [[ -n "$d" && -f "${d}/gamemd.exe" ]]; then
    FOUND+=("$d")
  fi
done

# Deduplicate
uniq_found=()
for d in "${FOUND[@]+"${FOUND[@]}"}"; do
  skip=0
  for u in "${uniq_found[@]+"${uniq_found[@]}"}"; do
    [[ "$u" == "$d" ]] && skip=1 && break
  done
  [[ $skip -eq 0 ]] && uniq_found+=("$d")
done

if [[ ${#uniq_found[@]} -eq 0 ]]; then
  cat <<EOF
No Yuri's Revenge install found (no gamemd.exe).

Searched Steam / CrossOver / Wine / ~/Games.
OpenRA Red Alert (RA1) is NOT a substitute.

When you have a legal YR directory:
  ./scripts/install-mod.sh --game-dir "/path/to/YR" --wire-includes
EOF
  exit 1
fi

GAME_DIR="${uniq_found[0]}"
{
  echo "# Auto-generated by scripts/detect-game.sh — local only, gitignored"
  echo "GAME_DIR=\"${GAME_DIR}\""
} >"$OUT"

echo "Found YR game dir: $GAME_DIR"
if [[ ${#uniq_found[@]} -gt 1 ]]; then
  echo "Also found:"
  for d in "${uniq_found[@]:1}"; do
    echo "  - $d"
  done
  echo "(Wrote first match to paths.local)"
fi
echo "paths.local updated. Install with:"
echo "  ./scripts/install-mod.sh --game-dir \"$GAME_DIR\" --wire-includes"
